title: AI&DB Conference Deadlines # (Maintained by @fukien)
# email: wentaohuang@ruc.edu.cn
description: Countdowns to top AI/DB/DM/IR/ML/NLP conference deadlines
author: Wentao Huang

domain: "fukien.github.io"
baseurl: "/ai-db-deadlines"

github_username: fukien
github_repo: ai-db-deadlines

markdown: kramdown
ga_id:

include: ['_pages']