title: DB-AI Conference Deadlines # (Maintained by @fukien)
# email: huangwentao@u.nus.edu
description: Countdowns to top DB/AI/DM/IR/ML/NLP conference deadlines
author: Wentao Huang

domain: "fukien.github.io"
baseurl: "/ai-db-deadlines"

github_username: fukien
github_repo: ai-db-deadlines

markdown: kramdown
ga_id:

include: ['_pages']