title: Deadline Countdowns # (Maintained by @fukien)
# email: huangwentao@u.nus.edu
description: Countdowns to some top tier computer science conference deadlines
author: Wentao Huang

domain: "fukien.github.io"
baseurl: "/deadline-countdowns"

github_username: fukien
github_repo: deadline-countdowns

markdown: kramdown
ga_id:

include: ['_pages']